# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dezine.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("MagicCoreMenu")
        Dialog.resize(679, 315)
        Dialog.setStyleSheet("background-color: #e6e6e6;\n"
"\n"
"")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 301, 61))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setStyleSheet("background-color: #ebebeb;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 311, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Server = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Server.setStyleSheet("background-color: #ffffff;\n"
"")
        self.Server.setObjectName("Server")
        self.horizontalLayout.addWidget(self.Server)
        self.Memory = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Memory.setStyleSheet("background-color: #ffffff;\\n")
        self.Memory.setObjectName("Memory")
        self.horizontalLayout.addWidget(self.Memory)
        self.Info = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.Info.setStyleSheet("background-color: #ffffff;\n"
"")
        self.Info.setObjectName("Info")
        self.horizontalLayout.addWidget(self.Info)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 0, 311, 16))
        self.line.setStyleSheet("background-color: #747474;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 300, 311, 16))
        self.line_2.setStyleSheet("background-color: #747474;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Logi = QtWidgets.QTextEdit(Dialog)
        self.Logi.setGeometry(QtCore.QRect(310, 0, 391, 321))
        self.Logi.setStyleSheet("background-color: #d1d1d1;\n"
"")
        self.Logi.setObjectName("Logi")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 150, 311, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Start = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Start.setStyleSheet("background-color: #5cb85c;\n"
"border-color: #4cae4c;")
        self.Start.setObjectName("Start")
        self.horizontalLayout_3.addWidget(self.Start)
        self.Stop = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Stop.setStyleSheet("background-color: #d9534f;\n"
"border-color: #d43f3a;")
        self.Stop.setObjectName("Stop")
        self.horizontalLayout_3.addWidget(self.Stop)
        self.Kill = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.Kill.setStyleSheet("background-color: #d9534f;\n"
"border-color: #d43f3a;")
        self.Kill.setObjectName("Kill")
        self.horizontalLayout_3.addWidget(self.Kill)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 210, 311, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton.setStyleSheet("background-color: #5cb85c;\n"
"border-color: #4cae4c;")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.Restart = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.Restart.setStyleSheet("background-color: #3c8dbc;\n"
"border-color: #2e6da4;")
        self.Restart.setObjectName("Restart")
        self.horizontalLayout_4.addWidget(self.Restart)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Server.setText(_translate("Dialog", "MagicCore:"))
        self.Memory.setText(_translate("Dialog", "Состояние"))
        self.Info.setText(_translate("Dialog", "Информация"))
        self.Start.setText(_translate("Dialog", "Старт"))
        self.Stop.setText(_translate("Dialog", "Стоп"))
        self.Kill.setText(_translate("Dialog", "Кильнуть"))
        self.pushButton.setText(_translate("Dialog", "Сохранить Мир"))
        self.Restart.setText(_translate("Dialog", "Рестарт"))

